# Name of Action workflow
name: Set - Get the Values
on: [workflow_dispatch]
      
# Jobs are listed to be run of GitHub runners. 
jobs:
   # JOB 1 : This job is to validate all the input values used in workflow. ********************************************************************************** *******************************************
    Job-1:
      runs-on: ubuntu-latest
      steps:      
      # Variable-setup
      - name: set-variables
        uses: actions/checkout@v1
      
      - uses: actions/upload-artifact@v2
        with:
            name: my-artifact
            path: packer/Variables.json

    # JOB 1 ENDS  *****************************************************************************************************************************
   
    # JOB 2 : This job is to Build packer image.********************************************************************************** *****************************************       
    Build-Image:
      name: Job-2
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo code
        uses: actions/checkout@v1
        
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.6"

      - name: Get-Variables
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
        
      - name: build custom image
        run: >
          packer build "-var-file=packer/Variables.json" packer/packer.json
        env:
            client-id: "d82451ce-9715-41d8-8007-a177082d6dd3"
            tenant-id: "411962c5-bfd8-43e3-b5a7-fac389f9d4ea"
            subscription-id: "60338480-8af5-4fc6-80fb-2715b3c42f42"
            client_secret: "EuW8Q~5xTryWaoPHB4aBglvsjvP232XVkbb.pbi0"

    # JOB 2 ENDS  ******************************************************************************************************************************
           
   
