# Name of Action workflow
name: Image Creation Pipeline
on: [workflow_dispatch]

permissions:
      id-token: write
      pages: write
      contents: read
      
# Jobs are listed to be run of GitHub runners. 
jobs:
   # JOB 1 : This job is to validate all the input values used in workflow. ***************************************** ***************************************** *******************************************
    Validate-Inputs:
      runs-on: ubuntu-latest
      steps:
      # Login to the Azure
      - name: Azure login
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true
            
        # Checkout repo code
      - name: Checkout repo code
        uses: actions/checkout@v1
        
        # Set Variables
      - name: set-variables
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: packer/Variables.json

    # JOB 1 ENDS  ***************************************** ***************************************** *******************************************
   
    # JOB 2 : This job is to Build packer image.********************************************************************************** *****************************************       
    Build-Image:
      name: charan
      runs-on: ubuntu-latest
      
     # Login to the Azure
      steps:
        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true
          env:
            PRODUCT_VERSION: "latest"

       # This task is setup the packer
        - name: Setup Packer
          uses: hashicorp/setup-packer@main
          id: setup
          with:
            version: "1.8.6"

        # This task is build the packer Image using GitHub secrets
        - name: build custom image
          run: >
                packer build -force "-var-file=Packer/Variables.json"  
    
        - name: Get-Variables
          uses: actions/download-artifact@v2
          with:
            name: my-artifact

    # JOB 2 ENDS  *********************************************************************************** *******************************************
           
   
