# Name of Action workflow
name: Set - Get the Values
on: [workflow_dispatch]
      
# Jobs are listed to be run of GitHub runners. 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Data
        uses: actions/cache@v2
        with:
          path: |
            path/to/data
          key: ${{ runner.os }}-data-${{ hashFiles('path/to/data/**') }}
          restore-keys: |
            ${{ runner.os }}-data-
            
  use-data:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Cached Data
        uses: actions/cache@v2
        with:
          path: |
            path/to/data
          key: ${{ runner.os }}-data-${{ hashFiles('path/to/data/**') }}


