# Name of Action workflow
name: Set - Get the Values
on: [workflow_dispatch]
      
# Jobs are listed to be run of GitHub runners. 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Data
        uses: actions/cache@v2
        with:
          path: |
            path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
  use-data:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes
          
      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: /generate-primes.sh -d prime-numbe


