name: Share Data Between Jobs

on: [workflow_dispatch]

jobs:
  generate-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate Data
      run: |
        # Your data generation steps here
        echo "Generated data" > generated-data.txt

    - name: Cache Data
      uses: actions/cache@v2
      with:
        path: |
          generated-data.txt
        key: ${{ runner.os }}-data-${{ hashFiles('generated-data.txt') }}

  use-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Restore Cached Data
      uses: actions/cache@v2
      with:
        path: |
          generated-data.txt
        key: ${{ runner.os }}-data-${{ hashFiles('generated-data.txt') }}

    - name: Use Data
      run: |
        # Your steps using the shared data
        cat generated-data.txt
