name: Packer Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: '1.8.3' 

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CRED}}

    - name: Build Packer image
      run: 
        packer build "-var-file=packer/Variables.json" packer/packer.json
